steps:
  # Check the Python version
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - python3 .cloud-build/CheckPythonVersion.py -q
  # Fetch full repo for diff purposes
  - name: gcr.io/cloud-builders/git
    args: [fetch, --unshallow, --quiet]
  # Create a virtual environment
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - python3 -m venv workspace/env
  # Install Python dependencies and run testing script
  - name: ${_PYTHON_IMAGE}
    entrypoint: /bin/sh
    args:
    - -c
    - |
      . workspace/env/bin/activate &&
      python3 notebooks/notebook_template_review.py --web --title --steps --desc --linkback --notebook-dir=notebooks/official >web.html
artifacts:
  objects:
          location: gs://${_GCS_ARTIFACTS_BUCKET}/webdoc
          paths: ['web.html']
timeout: 86400s
