steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'check-device-type-cpu'
  automapSubstitutions: true
  script: |
      #!/usr/bin/env bash
      base_image=''
      image_name=''
      device_type_param=${_DEVICE_TYPE}
      device_type=${device_type_param,,}
      if [[ $device_type == "cpu" ]]; then
        echo "Building container image for: $device_type"
        git clone https://github.com/vllm-project/vllm.git
        cd vllm && DOCKER_BUILDKIT=1 docker build -t vllm-cpu-base -f docker/Dockerfile.cpu .
        cd ..
        base_image='vllm-cpu-base'
        image_name='vllm-cpu'
      elif [[ $device_type == "gpu" ]]; then
        base_image='vllm/vllm-openai'
        image_name='vllm-gpu'
      elif [[ $device_type == "tpu" ]]; then
        base_image='vllm/vllm-tpu:nightly'
        image_name='vllm-tpu'
      fi
      docker build -t $LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$image_name --build-arg BASE_IMAGE=$base_image .
      docker push $LOCATION-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/$image_name
substitutions:
    _DEVICE_TYPE: cpu
    _REPOSITORY: my-docker-repo